### ISSUE TITLE
Unable to read the host file system while docker is running

### ISSUE THREAD

**Issue by walnut-tom** [toolkits/nux#29]
When reading files, the file path can be prefixed to adapt to the file system of the host in docker.

**Comment by UlricQin** [comment]
你这是要把agent跑到docker里？所有的/proc下的文件前面都直接加了一个`Root()+`，如果是docker里的话，这些/proc文件都在么？

**Comment by walnut-tom** [comment]
是的，特别是作为daemonset运行时，
这个是运行在docker里面监控主机，需要把主机的文件系统mount到docker里面的一个目录上，比如
sudo docker run --rm -e NUX_ROOTFS=/rootfs   -v /:/rootfs:r falcon-agnet，然后就可以读到host上的系统文件

**Comment by walnut-tom** [comment]
[open-falcon-agent是否可以DaemonSet方式部署在k8s集群里？](https://github.com/open-falcon/falcon-plus/issues/774)
